home:
  local: http://localhost/Phest/sites/skaura-matsuri/output/local
  production: http://www.skaura-matsuri.com
description: 
basetpl: _base.tpl
buildclear: 1
sitemap: 1
robotstxt: 1
compilejs: 1
compilecss: 1